CREATE TABLE `customer_orders` (
  `id` int NOT NULL AUTO_INCREMENT,
  `order_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '订单编号',
  `date` date NOT NULL COMMENT '日期',
  `is_fixed` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否定稿',
  `order_content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '稿件内容信息',
  `word_count` int DEFAULT NULL COMMENT '稿件字数(只填写数字)',
  `fee` decimal(10, 2) DEFAULT NULL COMMENT '稿费',
  `customer_id` int DEFAULT NULL COMMENT '客服ID',
  `writer_id` int DEFAULT NULL COMMENT '写手ID',
  `exchange_time` datetime DEFAULT NULL COMMENT '交稿时间',
  `payment_channel` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '付款渠道',
  `store_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '店铺名或客户线下',
  `new_customer` tinyint(1) DEFAULT '0' COMMENT '是否新客户',
  `order_amount` decimal(10, 2) DEFAULT NULL COMMENT '订单下单金额',
  `refund_amount` decimal(10, 2) DEFAULT '0.00' COMMENT '退款金额',
  `special_situation` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '特殊情况(不结算)',
  `customer_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '客户名称',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_order_id` (`order_id`),
  KEY `idx_date` (`date`),
  KEY `idx_customer_id` (`customer_id`),
  KEY `idx_writer_id` (`writer_id`),
  CONSTRAINT `fk_customer_order_customer` FOREIGN KEY (`customer_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_customer_order_writer` FOREIGN KEY (`writer_id`) REFERENCES `writer_info` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客服填报订单表'; 